# pull official base image
FROM node:16.14.2

# set working directory
WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --legacy-peer-deps
RUN npm install react-scripts --legacy-peer-deps

# add app
COPY . ./

# start app
CMD ["npm", "start"]  